### ISSUE TITLE
error creating NDArray

### ISSUE THREAD

**Issue by psteinb** [Blosc/blosc2_grok#11]
Hi, 
I wanted to give blosc2_grok a spin. When I run the example with blosc2_grok `0.3.3`, I get the following error:

``` shell
$ python ./examples/roundtrip.py examples/MI04_020751.tif
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/steinb95/development/blosc2_grok/blosc2_grok/__init__.py", line 112, in <module>
    lib = ctypes.cdll.LoadLibrary(libpath)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/steinb95/development/blosc2_grok/blosc2_grok/libblosc2_grok.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/steinb95/development/blosc2_grok/blosc2_grok/__init__.py", line 112, in <module>
    lib = ctypes.cdll.LoadLibrary(libpath)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/steinb95/development/blosc2_grok/blosc2_grok/libblosc2_grok.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/steinb95/development/blosc2_grok/./examples/roundtrip.py", line 77, in <module>
    array = compress(im, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steinb95/development/blosc2_grok/./examples/roundtrip.py", line 41, in compress
    bl_array = blosc2.asarray(
               ^^^^^^^^^^^^^^^
  File "/home/steinb95/development/blosc2_grok/py312/lib64/python3.12/site-packages/blosc2/ndarray.py", line 1266, in asarray
    return blosc2_ext.asarray(array, chunks, blocks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "blosc2_ext.pyx", line 2344, in blosc2.blosc2_ext.asarray
  File "blosc2_ext.pyx", line 1911, in blosc2.blosc2_ext._check_rc
RuntimeError: Error while creating the NDArray
```
This is with `Python 3.12.2 (main, Feb 21 2024, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)] on linux` on `fc39`.

**Comment by psteinb** [comment]
Steps to reproduce:
- `git clone git@github.com:Blosc/blosc2_grok.git`
- `cd blosc2_grok`
- `python -m venv py312 --upgrade-deps`
- `source py312/bin/activate`
- `python -m pip install blosc2_grok pillow`
- `python ./examples/roundtrip.py examples/MI04_020751.tif`

**Comment by FrancescAlted** [comment]
Hi Peter.  I think this is because python expects the extension to be in your local `blosc2_grok/` directory.  Try with:

```bash
cd examples
python roundtrip.py MI04_020751.tif
```
